### ISSUE TITLE
Question/Help

### ISSUE THREAD

**Issue by vackyton** [FogNetwork/Tsunami#5]
### Comment

My school blocked heroku :( can you use replit or smt and how does your proxy work?

**Comment by vackyton** [comment]
and also could you teach me how to make proxies and maybe i could help you?I can help you in adding friday night funking and heroku app is blocked but i can still use heroku i just can't see the finished product

**Comment by vackyton** [comment]
also btw smoke doesn't work so doesn't 1v1lol haven't tested others used replit
https://replit.com/@vackyton/Tsunami#index.js

**Comment by Nebelung-Dev** [comment]
None of the proxies have been added, I will add them soon but I working on the games right now. You can look at the pinned issue for a to do list. Smoke is still being worked on but will be ready soon. Replit works the same as heroku so it is fine to use that. Make an issue or pull if you have any requests

**Comment by vackyton** [comment]
can i join FogNetwork also my discord is Vackyton#6510
