### ISSUE TITLE
I can’t access discord… I’m on replit

### ISSUE THREAD

**Issue by Atlas-Can-Code** [FogNetwork/Tsunami#6]
The server runs and all, but I can’t get to discord, I just get whitescreened. I’m running off of replit, I’ve literally tried every single proxy offered but they don’t work. Any ideas?

**Comment by Nebelung-Dev** [comment]
That would be an issue with corrosion (the proxy that works with discord) I would try again later
https://github.com/titaniumnetwork-dev/Corrosion
